version: '2'

run:
  timeout: 2m
  tests: true
  build-tags:
    - codeanalysis

linters:
  enable:
    - staticcheck
    - govet
    - errcheck
    - unused
    - gosec
    - ineffassign

formatters:
  enable:
    - gofumpt
    - goimports
