version: '2'

run:
  timeout: 2m
  tests: true
  build-tags:
    - codeanalysis

linters:
  enable:
    - staticcheck
    - govet
    - errcheck
    - unused
    - gosec
    - ineffassign
  exclusions:
    rules:
      - linters:
          - gosec
        path: test/integration
        text: 'Binds to all network interfaces'

formatters:
  enable:
    - gofumpt
    - goimports
