// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: clavis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Clavis_Get_FullMethodName       = "/clavis.v1.Clavis/Get"
	Clavis_Set_FullMethodName       = "/clavis.v1.Clavis/Set"
	Clavis_Del_FullMethodName       = "/clavis.v1.Clavis/Del"
	Clavis_Ping_FullMethodName      = "/clavis.v1.Clavis/Ping"
	Clavis_ListPush_FullMethodName  = "/clavis.v1.Clavis/ListPush"
	Clavis_ListPop_FullMethodName   = "/clavis.v1.Clavis/ListPop"
	Clavis_ListLen_FullMethodName   = "/clavis.v1.Clavis/ListLen"
	Clavis_ListMove_FullMethodName  = "/clavis.v1.Clavis/ListMove"
	Clavis_ListRange_FullMethodName = "/clavis.v1.Clavis/ListRange"
	Clavis_ListTrim_FullMethodName  = "/clavis.v1.Clavis/ListTrim"
)

// ClavisClient is the client API for Clavis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClavisClient interface {
	// Get retrieves a value by its key.
	// Returns a response indicating whether the key was found and the value.
	// If the key does not exist, found will be false and value will be empty.
	// If the key exists, found will be true and value will contain the data.
	// If an error occurs, the response will contain an error message.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Set sets a value for a key.
	// If the key already exists, it can be set conditionally based
	// on flags (NX for "not exists", XX for "exists").
	// The response will indicate success or failure,
	// and can optionally return the old value if the key existed.
	// If an error occurs, the response will contain an error message.
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	// Del deletes a key.
	// Returns a response indicating whether the deletion was successful.
	// If the key does not exist, success is false and error contains a message.
	// If the key exists and is deleted, success is true and error is empty.
	// If an error occurs, the response will contain an error message.
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
	// Ping checks the connection to the server.
	// Returns a simple acknowledgment message.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// ListPush pushes one or more values to the left end of a list.
	// Returns the length of the list after the operation.
	ListPush(ctx context.Context, in *ListPushRequest, opts ...grpc.CallOption) (*ListPushResponse, error)
	// ListPop pops the first element from a list.
	// Returns the popped value or an error if the list is
	// empty or does not exist.
	ListPop(ctx context.Context, in *ListPopRequest, opts ...grpc.CallOption) (*ListPopResponse, error)
	// ListLen retrieves the length of a list.
	// Returns the length or an error if the key does not exist or is not a list
	ListLen(ctx context.Context, in *ListLenRequest, opts ...grpc.CallOption) (*ListLenResponse, error)
	// ListMove moves an element from one list to another.
	// The element is moved from the specified side of the source
	// list to the specified side of the destination list.
	// Returns the moved element or an error if the source list is
	// empty or does not exist
	ListMove(ctx context.Context, in *ListMoveRequest, opts ...grpc.CallOption) (*ListMoveResponse, error)
	// ListRange retrieves a range of elements from a list.
	// The range is specified by start and end indices.
	// Returns the elements in the specified range or an
	// error if the key does not exist or
	// is not a list.
	ListRange(ctx context.Context, in *ListRangeRequest, opts ...grpc.CallOption) (*ListRangeResponse, error)
	// ListTrim trims a list to the specified range.
	// The range is specified by start and stop indices.
	// Returns an acknowledgment on success or an error
	// if the key does not exist or is not
	// a list.
	ListTrim(ctx context.Context, in *ListTrimRequest, opts ...grpc.CallOption) (*ListTrimResponse, error)
}

type clavisClient struct {
	cc grpc.ClientConnInterface
}

func NewClavisClient(cc grpc.ClientConnInterface) ClavisClient {
	return &clavisClient{cc}
}

func (c *clavisClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Clavis_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, Clavis_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, Clavis_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Clavis_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) ListPush(ctx context.Context, in *ListPushRequest, opts ...grpc.CallOption) (*ListPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPushResponse)
	err := c.cc.Invoke(ctx, Clavis_ListPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) ListPop(ctx context.Context, in *ListPopRequest, opts ...grpc.CallOption) (*ListPopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPopResponse)
	err := c.cc.Invoke(ctx, Clavis_ListPop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) ListLen(ctx context.Context, in *ListLenRequest, opts ...grpc.CallOption) (*ListLenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLenResponse)
	err := c.cc.Invoke(ctx, Clavis_ListLen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) ListMove(ctx context.Context, in *ListMoveRequest, opts ...grpc.CallOption) (*ListMoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMoveResponse)
	err := c.cc.Invoke(ctx, Clavis_ListMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) ListRange(ctx context.Context, in *ListRangeRequest, opts ...grpc.CallOption) (*ListRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRangeResponse)
	err := c.cc.Invoke(ctx, Clavis_ListRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) ListTrim(ctx context.Context, in *ListTrimRequest, opts ...grpc.CallOption) (*ListTrimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrimResponse)
	err := c.cc.Invoke(ctx, Clavis_ListTrim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClavisServer is the server API for Clavis service.
// All implementations must embed UnimplementedClavisServer
// for forward compatibility.
type ClavisServer interface {
	// Get retrieves a value by its key.
	// Returns a response indicating whether the key was found and the value.
	// If the key does not exist, found will be false and value will be empty.
	// If the key exists, found will be true and value will contain the data.
	// If an error occurs, the response will contain an error message.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Set sets a value for a key.
	// If the key already exists, it can be set conditionally based
	// on flags (NX for "not exists", XX for "exists").
	// The response will indicate success or failure,
	// and can optionally return the old value if the key existed.
	// If an error occurs, the response will contain an error message.
	Set(context.Context, *SetRequest) (*SetResponse, error)
	// Del deletes a key.
	// Returns a response indicating whether the deletion was successful.
	// If the key does not exist, success is false and error contains a message.
	// If the key exists and is deleted, success is true and error is empty.
	// If an error occurs, the response will contain an error message.
	Del(context.Context, *DelRequest) (*DelResponse, error)
	// Ping checks the connection to the server.
	// Returns a simple acknowledgment message.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// ListPush pushes one or more values to the left end of a list.
	// Returns the length of the list after the operation.
	ListPush(context.Context, *ListPushRequest) (*ListPushResponse, error)
	// ListPop pops the first element from a list.
	// Returns the popped value or an error if the list is
	// empty or does not exist.
	ListPop(context.Context, *ListPopRequest) (*ListPopResponse, error)
	// ListLen retrieves the length of a list.
	// Returns the length or an error if the key does not exist or is not a list
	ListLen(context.Context, *ListLenRequest) (*ListLenResponse, error)
	// ListMove moves an element from one list to another.
	// The element is moved from the specified side of the source
	// list to the specified side of the destination list.
	// Returns the moved element or an error if the source list is
	// empty or does not exist
	ListMove(context.Context, *ListMoveRequest) (*ListMoveResponse, error)
	// ListRange retrieves a range of elements from a list.
	// The range is specified by start and end indices.
	// Returns the elements in the specified range or an
	// error if the key does not exist or
	// is not a list.
	ListRange(context.Context, *ListRangeRequest) (*ListRangeResponse, error)
	// ListTrim trims a list to the specified range.
	// The range is specified by start and stop indices.
	// Returns an acknowledgment on success or an error
	// if the key does not exist or is not
	// a list.
	ListTrim(context.Context, *ListTrimRequest) (*ListTrimResponse, error)
	mustEmbedUnimplementedClavisServer()
}

// UnimplementedClavisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClavisServer struct{}

func (UnimplementedClavisServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedClavisServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedClavisServer) Del(context.Context, *DelRequest) (*DelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedClavisServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedClavisServer) ListPush(context.Context, *ListPushRequest) (*ListPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPush not implemented")
}
func (UnimplementedClavisServer) ListPop(context.Context, *ListPopRequest) (*ListPopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPop not implemented")
}
func (UnimplementedClavisServer) ListLen(context.Context, *ListLenRequest) (*ListLenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLen not implemented")
}
func (UnimplementedClavisServer) ListMove(context.Context, *ListMoveRequest) (*ListMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMove not implemented")
}
func (UnimplementedClavisServer) ListRange(context.Context, *ListRangeRequest) (*ListRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRange not implemented")
}
func (UnimplementedClavisServer) ListTrim(context.Context, *ListTrimRequest) (*ListTrimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrim not implemented")
}
func (UnimplementedClavisServer) mustEmbedUnimplementedClavisServer() {}
func (UnimplementedClavisServer) testEmbeddedByValue()                {}

// UnsafeClavisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClavisServer will
// result in compilation errors.
type UnsafeClavisServer interface {
	mustEmbedUnimplementedClavisServer()
}

func RegisterClavisServer(s grpc.ServiceRegistrar, srv ClavisServer) {
	// If the following call pancis, it indicates UnimplementedClavisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Clavis_ServiceDesc, srv)
}

func _Clavis_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_ListPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).ListPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_ListPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).ListPush(ctx, req.(*ListPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_ListPop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).ListPop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_ListPop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).ListPop(ctx, req.(*ListPopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_ListLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).ListLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_ListLen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).ListLen(ctx, req.(*ListLenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_ListMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).ListMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_ListMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).ListMove(ctx, req.(*ListMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_ListRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).ListRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_ListRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).ListRange(ctx, req.(*ListRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_ListTrim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).ListTrim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_ListTrim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).ListTrim(ctx, req.(*ListTrimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Clavis_ServiceDesc is the grpc.ServiceDesc for Clavis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clavis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clavis.v1.Clavis",
	HandlerType: (*ClavisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Clavis_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Clavis_Set_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Clavis_Del_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Clavis_Ping_Handler,
		},
		{
			MethodName: "ListPush",
			Handler:    _Clavis_ListPush_Handler,
		},
		{
			MethodName: "ListPop",
			Handler:    _Clavis_ListPop_Handler,
		},
		{
			MethodName: "ListLen",
			Handler:    _Clavis_ListLen_Handler,
		},
		{
			MethodName: "ListMove",
			Handler:    _Clavis_ListMove_Handler,
		},
		{
			MethodName: "ListRange",
			Handler:    _Clavis_ListRange_Handler,
		},
		{
			MethodName: "ListTrim",
			Handler:    _Clavis_ListTrim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clavis.proto",
}
