// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: clavis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Side indicates the side of a list (LEFT or RIGHT)
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0 // Default value, should not be used
	Side_SIDE_LEFT        Side = 1
	Side_SIDE_RIGHT       Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_LEFT",
		2: "SIDE_RIGHT",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_LEFT":        1,
		"SIDE_RIGHT":       2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_clavis_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_clavis_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{0}
}

// Empty message for requests that do not require parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_clavis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key whose value to retrieve
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_clavis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetResponse_Value
	//	*GetResponse_NotFound
	//	*GetResponse_Error
	Result        isGetResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_clavis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetResult() isGetResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		if x, ok := x.Result.(*GetResponse_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *GetResponse) GetNotFound() *Empty {
	if x != nil {
		if x, ok := x.Result.(*GetResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *GetResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*GetResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isGetResponse_Result interface {
	isGetResponse_Result()
}

type GetResponse_Value struct {
	// If the key exists, its value (arbitrary binary/text)
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type GetResponse_NotFound struct {
	// If the key does not exist
	NotFound *Empty `protobuf:"bytes,2,opt,name=not_found,json=notFound,proto3,oneof"`
}

type GetResponse_Error struct {
	// If an error occurred
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*GetResponse_Value) isGetResponse_Result() {}

func (*GetResponse_NotFound) isGetResponse_Result() {}

func (*GetResponse_Error) isGetResponse_Result() {}

type SetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to set
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value to associate with the key
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Types that are valid to be assigned to Flags:
	//
	//	*SetRequest_Create
	//	*SetRequest_Update
	Flags isSetRequest_Flags `protobuf_oneof:"flags"`
	// Return the old value if the key already exists
	Get bool `protobuf:"varint,5,opt,name=get,proto3" json:"get,omitempty"`
	// Optional expiration. Only one may be set.
	//
	// Types that are valid to be assigned to Expiration:
	//
	//	*SetRequest_Seconds
	//	*SetRequest_Milliseconds
	//	*SetRequest_UnixSeconds
	//	*SetRequest_UnixMilliseconds
	//	*SetRequest_KeepTtl
	Expiration    isSetRequest_Expiration `protobuf_oneof:"expiration"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_clavis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{3}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetFlags() isSetRequest_Flags {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *SetRequest) GetCreate() bool {
	if x != nil {
		if x, ok := x.Flags.(*SetRequest_Create); ok {
			return x.Create
		}
	}
	return false
}

func (x *SetRequest) GetUpdate() bool {
	if x != nil {
		if x, ok := x.Flags.(*SetRequest_Update); ok {
			return x.Update
		}
	}
	return false
}

func (x *SetRequest) GetGet() bool {
	if x != nil {
		return x.Get
	}
	return false
}

func (x *SetRequest) GetExpiration() isSetRequest_Expiration {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *SetRequest) GetSeconds() uint32 {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_Seconds); ok {
			return x.Seconds
		}
	}
	return 0
}

func (x *SetRequest) GetMilliseconds() uint64 {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_Milliseconds); ok {
			return x.Milliseconds
		}
	}
	return 0
}

func (x *SetRequest) GetUnixSeconds() uint64 {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_UnixSeconds); ok {
			return x.UnixSeconds
		}
	}
	return 0
}

func (x *SetRequest) GetUnixMilliseconds() uint64 {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_UnixMilliseconds); ok {
			return x.UnixMilliseconds
		}
	}
	return 0
}

func (x *SetRequest) GetKeepTtl() bool {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_KeepTtl); ok {
			return x.KeepTtl
		}
	}
	return false
}

type isSetRequest_Flags interface {
	isSetRequest_Flags()
}

type SetRequest_Create struct {
	// Set the key only if it does not already exist
	Create bool `protobuf:"varint,3,opt,name=create,proto3,oneof"`
}

type SetRequest_Update struct {
	// Set the key only if it already exists
	Update bool `protobuf:"varint,4,opt,name=update,proto3,oneof"`
}

func (*SetRequest_Create) isSetRequest_Flags() {}

func (*SetRequest_Update) isSetRequest_Flags() {}

type isSetRequest_Expiration interface {
	isSetRequest_Expiration()
}

type SetRequest_Seconds struct {
	// Expire after this many seconds
	Seconds uint32 `protobuf:"varint,6,opt,name=seconds,proto3,oneof"`
}

type SetRequest_Milliseconds struct {
	// Expire after this many milliseconds
	Milliseconds uint64 `protobuf:"varint,7,opt,name=milliseconds,proto3,oneof"`
}

type SetRequest_UnixSeconds struct {
	// Set the specific expiration time
	UnixSeconds uint64 `protobuf:"varint,8,opt,name=unix_seconds,json=unixSeconds,proto3,oneof"`
}

type SetRequest_UnixMilliseconds struct {
	// Set the specific expiration time in milliseconds
	UnixMilliseconds uint64 `protobuf:"varint,9,opt,name=unix_milliseconds,json=unixMilliseconds,proto3,oneof"`
}

type SetRequest_KeepTtl struct {
	// Keep the key alive indefinitely
	KeepTtl bool `protobuf:"varint,10,opt,name=keep_ttl,json=keepTtl,proto3,oneof"`
}

func (*SetRequest_Seconds) isSetRequest_Expiration() {}

func (*SetRequest_Milliseconds) isSetRequest_Expiration() {}

func (*SetRequest_UnixSeconds) isSetRequest_Expiration() {}

func (*SetRequest_UnixMilliseconds) isSetRequest_Expiration() {}

func (*SetRequest_KeepTtl) isSetRequest_Expiration() {}

type SetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OK on success, or an error message
	//
	// Types that are valid to be assigned to Result:
	//
	//	*SetResponse_Ok
	//	*SetResponse_Error
	Result        isSetResponse_Result `protobuf_oneof:"result"`
	OldValue      []byte               `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3,oneof" json:"old_value,omitempty"` // Old value if get was true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_clavis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{4}
}

func (x *SetResponse) GetResult() isSetResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SetResponse) GetOk() string {
	if x != nil {
		if x, ok := x.Result.(*SetResponse_Ok); ok {
			return x.Ok
		}
	}
	return ""
}

func (x *SetResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*SetResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *SetResponse) GetOldValue() []byte {
	if x != nil {
		return x.OldValue
	}
	return nil
}

type isSetResponse_Result interface {
	isSetResponse_Result()
}

type SetResponse_Ok struct {
	Ok string `protobuf:"bytes,1,opt,name=ok,proto3,oneof"` // usually "OK"
}

type SetResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Redis error reply
}

func (*SetResponse_Ok) isSetResponse_Result() {}

func (*SetResponse_Error) isSetResponse_Result() {}

type DelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to delete
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_clavis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{5}
}

func (x *DelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates whether the deletion was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation fails
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_clavis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{6}
}

func (x *DelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_clavis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{7}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response to a ping request, typically just an acknowledgment
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // e.g., "PONG"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_clavis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list to which values will be pushed
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Values to push to the list
	Values        [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"` // Values to push to the list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPushRequest) Reset() {
	*x = ListPushRequest{}
	mi := &file_clavis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPushRequest) ProtoMessage() {}

func (x *ListPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPushRequest.ProtoReflect.Descriptor instead.
func (*ListPushRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{9}
}

func (x *ListPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListPushRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type ListPushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListPushResponse_ListLength
	//	*ListPushResponse_Error
	Result        isListPushResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPushResponse) Reset() {
	*x = ListPushResponse{}
	mi := &file_clavis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPushResponse) ProtoMessage() {}

func (x *ListPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPushResponse.ProtoReflect.Descriptor instead.
func (*ListPushResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{10}
}

func (x *ListPushResponse) GetResult() isListPushResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListPushResponse) GetListLength() int64 {
	if x != nil {
		if x, ok := x.Result.(*ListPushResponse_ListLength); ok {
			return x.ListLength
		}
	}
	return 0
}

func (x *ListPushResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ListPushResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isListPushResponse_Result interface {
	isListPushResponse_Result()
}

type ListPushResponse_ListLength struct {
	// Length of the list after push
	ListLength int64 `protobuf:"varint,1,opt,name=list_length,json=listLength,proto3,oneof"`
}

type ListPushResponse_Error struct {
	// If the key does not exist or is not a list
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListPushResponse_ListLength) isListPushResponse_Result() {}

func (*ListPushResponse_Error) isListPushResponse_Result() {}

type ListPopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list from which to pop the first element
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPopRequest) Reset() {
	*x = ListPopRequest{}
	mi := &file_clavis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopRequest) ProtoMessage() {}

func (x *ListPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopRequest.ProtoReflect.Descriptor instead.
func (*ListPopRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{11}
}

func (x *ListPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListPopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListPopResponse_Value
	//	*ListPopResponse_NotFound
	//	*ListPopResponse_Error
	Result        isListPopResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPopResponse) Reset() {
	*x = ListPopResponse{}
	mi := &file_clavis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopResponse) ProtoMessage() {}

func (x *ListPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopResponse.ProtoReflect.Descriptor instead.
func (*ListPopResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{12}
}

func (x *ListPopResponse) GetResult() isListPopResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListPopResponse) GetValue() []byte {
	if x != nil {
		if x, ok := x.Result.(*ListPopResponse_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *ListPopResponse) GetNotFound() *Empty {
	if x != nil {
		if x, ok := x.Result.(*ListPopResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *ListPopResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ListPopResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isListPopResponse_Result interface {
	isListPopResponse_Result()
}

type ListPopResponse_Value struct {
	// First element popped
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type ListPopResponse_NotFound struct {
	// If list is empty or key doesn't exist
	NotFound *Empty `protobuf:"bytes,2,opt,name=not_found,json=notFound,proto3,oneof"`
}

type ListPopResponse_Error struct {
	// If an error occurred
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ListPopResponse_Value) isListPopResponse_Result() {}

func (*ListPopResponse_NotFound) isListPopResponse_Result() {}

func (*ListPopResponse_Error) isListPopResponse_Result() {}

type ListLenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list whose length to retrieve
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLenRequest) Reset() {
	*x = ListLenRequest{}
	mi := &file_clavis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLenRequest) ProtoMessage() {}

func (x *ListLenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLenRequest.ProtoReflect.Descriptor instead.
func (*ListLenRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{13}
}

func (x *ListLenRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListLenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListLenResponse_Length
	//	*ListLenResponse_Error
	Result        isListLenResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLenResponse) Reset() {
	*x = ListLenResponse{}
	mi := &file_clavis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLenResponse) ProtoMessage() {}

func (x *ListLenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLenResponse.ProtoReflect.Descriptor instead.
func (*ListLenResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{14}
}

func (x *ListLenResponse) GetResult() isListLenResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListLenResponse) GetLength() int64 {
	if x != nil {
		if x, ok := x.Result.(*ListLenResponse_Length); ok {
			return x.Length
		}
	}
	return 0
}

func (x *ListLenResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ListLenResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isListLenResponse_Result interface {
	isListLenResponse_Result()
}

type ListLenResponse_Length struct {
	// Length of the list
	Length int64 `protobuf:"varint,1,opt,name=length,proto3,oneof"`
}

type ListLenResponse_Error struct {
	// If the key does not exist or is not a list
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListLenResponse_Length) isListLenResponse_Result() {}

func (*ListLenResponse_Error) isListLenResponse_Result() {}

type ListMoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The keys of the source and destination lists
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// The key of the destination list
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	// LEFT or RIGHT
	From Side `protobuf:"varint,3,opt,name=from,proto3,enum=clavis.v1.Side" json:"from,omitempty"`
	// LEFT or RIGHT
	To            Side `protobuf:"varint,4,opt,name=to,proto3,enum=clavis.v1.Side" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoveRequest) Reset() {
	*x = ListMoveRequest{}
	mi := &file_clavis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoveRequest) ProtoMessage() {}

func (x *ListMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoveRequest.ProtoReflect.Descriptor instead.
func (*ListMoveRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{15}
}

func (x *ListMoveRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListMoveRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *ListMoveRequest) GetFrom() Side {
	if x != nil {
		return x.From
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *ListMoveRequest) GetTo() Side {
	if x != nil {
		return x.To
	}
	return Side_SIDE_UNSPECIFIED
}

type ListMoveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListMoveResponse_MovedElement
	//	*ListMoveResponse_NotFound
	//	*ListMoveResponse_Error
	Result        isListMoveResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoveResponse) Reset() {
	*x = ListMoveResponse{}
	mi := &file_clavis_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoveResponse) ProtoMessage() {}

func (x *ListMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoveResponse.ProtoReflect.Descriptor instead.
func (*ListMoveResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{16}
}

func (x *ListMoveResponse) GetResult() isListMoveResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListMoveResponse) GetMovedElement() []byte {
	if x != nil {
		if x, ok := x.Result.(*ListMoveResponse_MovedElement); ok {
			return x.MovedElement
		}
	}
	return nil
}

func (x *ListMoveResponse) GetNotFound() *Empty {
	if x != nil {
		if x, ok := x.Result.(*ListMoveResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *ListMoveResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ListMoveResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isListMoveResponse_Result interface {
	isListMoveResponse_Result()
}

type ListMoveResponse_MovedElement struct {
	// The element moved from source to destination
	MovedElement []byte `protobuf:"bytes,1,opt,name=moved_element,json=movedElement,proto3,oneof"`
}

type ListMoveResponse_NotFound struct {
	// If the source list is empty or does not exist
	NotFound *Empty `protobuf:"bytes,2,opt,name=not_found,json=notFound,proto3,oneof"`
}

type ListMoveResponse_Error struct {
	// If an error occurred
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ListMoveResponse_MovedElement) isListMoveResponse_Result() {}

func (*ListMoveResponse_NotFound) isListMoveResponse_Result() {}

func (*ListMoveResponse_Error) isListMoveResponse_Result() {}

type ListRangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list to retrieve elements from
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Start index (inclusive)
	Start int64 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	// End index (inclusive)
	End           int64 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRangeRequest) Reset() {
	*x = ListRangeRequest{}
	mi := &file_clavis_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRangeRequest) ProtoMessage() {}

func (x *ListRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRangeRequest.ProtoReflect.Descriptor instead.
func (*ListRangeRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{17}
}

func (x *ListRangeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListRangeRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ListRangeRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type ListRangeData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The elements in the specified range
	Elements      [][]byte `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRangeData) Reset() {
	*x = ListRangeData{}
	mi := &file_clavis_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRangeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRangeData) ProtoMessage() {}

func (x *ListRangeData) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRangeData.ProtoReflect.Descriptor instead.
func (*ListRangeData) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{18}
}

func (x *ListRangeData) GetElements() [][]byte {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ListRangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListRangeResponse_Data
	//	*ListRangeResponse_Error
	Result        isListRangeResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRangeResponse) Reset() {
	*x = ListRangeResponse{}
	mi := &file_clavis_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRangeResponse) ProtoMessage() {}

func (x *ListRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRangeResponse.ProtoReflect.Descriptor instead.
func (*ListRangeResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{19}
}

func (x *ListRangeResponse) GetResult() isListRangeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListRangeResponse) GetData() *ListRangeData {
	if x != nil {
		if x, ok := x.Result.(*ListRangeResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ListRangeResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ListRangeResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isListRangeResponse_Result interface {
	isListRangeResponse_Result()
}

type ListRangeResponse_Data struct {
	// The elements in the specified range
	Data *ListRangeData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ListRangeResponse_Error struct {
	// If the key does not exist or is not a list
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListRangeResponse_Data) isListRangeResponse_Result() {}

func (*ListRangeResponse_Error) isListRangeResponse_Result() {}

type ListTrimRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list to trim
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Start index (inclusive)
	Start int64 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	// End index (inclusive)
	Stop          int64 `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrimRequest) Reset() {
	*x = ListTrimRequest{}
	mi := &file_clavis_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrimRequest) ProtoMessage() {}

func (x *ListTrimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrimRequest.ProtoReflect.Descriptor instead.
func (*ListTrimRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{20}
}

func (x *ListTrimRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListTrimRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ListTrimRequest) GetStop() int64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

type ListTrimResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListTrimResponse_Ok
	//	*ListTrimResponse_Error
	Result        isListTrimResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrimResponse) Reset() {
	*x = ListTrimResponse{}
	mi := &file_clavis_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrimResponse) ProtoMessage() {}

func (x *ListTrimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrimResponse.ProtoReflect.Descriptor instead.
func (*ListTrimResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{21}
}

func (x *ListTrimResponse) GetResult() isListTrimResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListTrimResponse) GetOk() string {
	if x != nil {
		if x, ok := x.Result.(*ListTrimResponse_Ok); ok {
			return x.Ok
		}
	}
	return ""
}

func (x *ListTrimResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ListTrimResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isListTrimResponse_Result interface {
	isListTrimResponse_Result()
}

type ListTrimResponse_Ok struct {
	Ok string `protobuf:"bytes,1,opt,name=ok,proto3,oneof"` // usually "OK"
}

type ListTrimResponse_Error struct {
	// If the key does not exist or is not a list
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListTrimResponse_Ok) isListTrimResponse_Result() {}

func (*ListTrimResponse_Error) isListTrimResponse_Result() {}

var File_clavis_proto protoreflect.FileDescriptor

const file_clavis_proto_rawDesc = "" +
	"\n" +
	"\fclavis.proto\x12\tclavis.v1\"\a\n" +
	"\x05Empty\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"x\n" +
	"\vGetResponse\x12\x16\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x12/\n" +
	"\tnot_found\x18\x02 \x01(\v2\x10.clavis.v1.EmptyH\x00R\bnotFound\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"\xc4\x02\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\x06create\x18\x03 \x01(\bH\x00R\x06create\x12\x18\n" +
	"\x06update\x18\x04 \x01(\bH\x00R\x06update\x12\x10\n" +
	"\x03get\x18\x05 \x01(\bR\x03get\x12\x1a\n" +
	"\aseconds\x18\x06 \x01(\rH\x01R\aseconds\x12$\n" +
	"\fmilliseconds\x18\a \x01(\x04H\x01R\fmilliseconds\x12#\n" +
	"\funix_seconds\x18\b \x01(\x04H\x01R\vunixSeconds\x12-\n" +
	"\x11unix_milliseconds\x18\t \x01(\x04H\x01R\x10unixMilliseconds\x12\x1b\n" +
	"\bkeep_ttl\x18\n" +
	" \x01(\bH\x01R\akeepTtlB\a\n" +
	"\x05flagsB\f\n" +
	"\n" +
	"expiration\"q\n" +
	"\vSetResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\tH\x00R\x02ok\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x12 \n" +
	"\told_value\x18\x03 \x01(\fH\x01R\boldValue\x88\x01\x01B\b\n" +
	"\x06resultB\f\n" +
	"\n" +
	"_old_value\"\x1e\n" +
	"\n" +
	"DelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"=\n" +
	"\vDelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\";\n" +
	"\x0fListPushRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\fR\x06values\"W\n" +
	"\x10ListPushResponse\x12!\n" +
	"\vlist_length\x18\x01 \x01(\x03H\x00R\n" +
	"listLength\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"\"\n" +
	"\x0eListPopRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"|\n" +
	"\x0fListPopResponse\x12\x16\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x12/\n" +
	"\tnot_found\x18\x02 \x01(\v2\x10.clavis.v1.EmptyH\x00R\bnotFound\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"\"\n" +
	"\x0eListLenRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"M\n" +
	"\x0fListLenResponse\x12\x18\n" +
	"\x06length\x18\x01 \x01(\x03H\x00R\x06length\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"\x91\x01\n" +
	"\x0fListMoveRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12#\n" +
	"\x04from\x18\x03 \x01(\x0e2\x0f.clavis.v1.SideR\x04from\x12\x1f\n" +
	"\x02to\x18\x04 \x01(\x0e2\x0f.clavis.v1.SideR\x02to\"\x8c\x01\n" +
	"\x10ListMoveResponse\x12%\n" +
	"\rmoved_element\x18\x01 \x01(\fH\x00R\fmovedElement\x12/\n" +
	"\tnot_found\x18\x02 \x01(\v2\x10.clavis.v1.EmptyH\x00R\bnotFound\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"L\n" +
	"\x10ListRangeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x03R\x03end\"+\n" +
	"\rListRangeData\x12\x1a\n" +
	"\belements\x18\x01 \x03(\fR\belements\"e\n" +
	"\x11ListRangeResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x18.clavis.v1.ListRangeDataH\x00R\x04data\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"M\n" +
	"\x0fListTrimRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x12\n" +
	"\x04stop\x18\x03 \x01(\x03R\x04stop\"F\n" +
	"\x10ListTrimResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\tH\x00R\x02ok\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result*;\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSIDE_LEFT\x10\x01\x12\x0e\n" +
	"\n" +
	"SIDE_RIGHT\x10\x022\x92\x05\n" +
	"\x06Clavis\x126\n" +
	"\x03Get\x12\x15.clavis.v1.GetRequest\x1a\x16.clavis.v1.GetResponse\"\x00\x126\n" +
	"\x03Set\x12\x15.clavis.v1.SetRequest\x1a\x16.clavis.v1.SetResponse\"\x00\x126\n" +
	"\x03Del\x12\x15.clavis.v1.DelRequest\x1a\x16.clavis.v1.DelResponse\"\x00\x129\n" +
	"\x04Ping\x12\x16.clavis.v1.PingRequest\x1a\x17.clavis.v1.PingResponse\"\x00\x12E\n" +
	"\bListPush\x12\x1a.clavis.v1.ListPushRequest\x1a\x1b.clavis.v1.ListPushResponse\"\x00\x12B\n" +
	"\aListPop\x12\x19.clavis.v1.ListPopRequest\x1a\x1a.clavis.v1.ListPopResponse\"\x00\x12B\n" +
	"\aListLen\x12\x19.clavis.v1.ListLenRequest\x1a\x1a.clavis.v1.ListLenResponse\"\x00\x12E\n" +
	"\bListMove\x12\x1a.clavis.v1.ListMoveRequest\x1a\x1b.clavis.v1.ListMoveResponse\"\x00\x12H\n" +
	"\tListRange\x12\x1b.clavis.v1.ListRangeRequest\x1a\x1c.clavis.v1.ListRangeResponse\"\x00\x12E\n" +
	"\bListTrim\x12\x1a.clavis.v1.ListTrimRequest\x1a\x1b.clavis.v1.ListTrimResponse\"\x00B\vZ\tpkg/protob\x06proto3"

var (
	file_clavis_proto_rawDescOnce sync.Once
	file_clavis_proto_rawDescData []byte
)

func file_clavis_proto_rawDescGZIP() []byte {
	file_clavis_proto_rawDescOnce.Do(func() {
		file_clavis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavis_proto_rawDesc), len(file_clavis_proto_rawDesc)))
	})
	return file_clavis_proto_rawDescData
}

var file_clavis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clavis_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_clavis_proto_goTypes = []any{
	(Side)(0),                 // 0: clavis.v1.Side
	(*Empty)(nil),             // 1: clavis.v1.Empty
	(*GetRequest)(nil),        // 2: clavis.v1.GetRequest
	(*GetResponse)(nil),       // 3: clavis.v1.GetResponse
	(*SetRequest)(nil),        // 4: clavis.v1.SetRequest
	(*SetResponse)(nil),       // 5: clavis.v1.SetResponse
	(*DelRequest)(nil),        // 6: clavis.v1.DelRequest
	(*DelResponse)(nil),       // 7: clavis.v1.DelResponse
	(*PingRequest)(nil),       // 8: clavis.v1.PingRequest
	(*PingResponse)(nil),      // 9: clavis.v1.PingResponse
	(*ListPushRequest)(nil),   // 10: clavis.v1.ListPushRequest
	(*ListPushResponse)(nil),  // 11: clavis.v1.ListPushResponse
	(*ListPopRequest)(nil),    // 12: clavis.v1.ListPopRequest
	(*ListPopResponse)(nil),   // 13: clavis.v1.ListPopResponse
	(*ListLenRequest)(nil),    // 14: clavis.v1.ListLenRequest
	(*ListLenResponse)(nil),   // 15: clavis.v1.ListLenResponse
	(*ListMoveRequest)(nil),   // 16: clavis.v1.ListMoveRequest
	(*ListMoveResponse)(nil),  // 17: clavis.v1.ListMoveResponse
	(*ListRangeRequest)(nil),  // 18: clavis.v1.ListRangeRequest
	(*ListRangeData)(nil),     // 19: clavis.v1.ListRangeData
	(*ListRangeResponse)(nil), // 20: clavis.v1.ListRangeResponse
	(*ListTrimRequest)(nil),   // 21: clavis.v1.ListTrimRequest
	(*ListTrimResponse)(nil),  // 22: clavis.v1.ListTrimResponse
}
var file_clavis_proto_depIdxs = []int32{
	1,  // 0: clavis.v1.GetResponse.not_found:type_name -> clavis.v1.Empty
	1,  // 1: clavis.v1.ListPopResponse.not_found:type_name -> clavis.v1.Empty
	0,  // 2: clavis.v1.ListMoveRequest.from:type_name -> clavis.v1.Side
	0,  // 3: clavis.v1.ListMoveRequest.to:type_name -> clavis.v1.Side
	1,  // 4: clavis.v1.ListMoveResponse.not_found:type_name -> clavis.v1.Empty
	19, // 5: clavis.v1.ListRangeResponse.data:type_name -> clavis.v1.ListRangeData
	2,  // 6: clavis.v1.Clavis.Get:input_type -> clavis.v1.GetRequest
	4,  // 7: clavis.v1.Clavis.Set:input_type -> clavis.v1.SetRequest
	6,  // 8: clavis.v1.Clavis.Del:input_type -> clavis.v1.DelRequest
	8,  // 9: clavis.v1.Clavis.Ping:input_type -> clavis.v1.PingRequest
	10, // 10: clavis.v1.Clavis.ListPush:input_type -> clavis.v1.ListPushRequest
	12, // 11: clavis.v1.Clavis.ListPop:input_type -> clavis.v1.ListPopRequest
	14, // 12: clavis.v1.Clavis.ListLen:input_type -> clavis.v1.ListLenRequest
	16, // 13: clavis.v1.Clavis.ListMove:input_type -> clavis.v1.ListMoveRequest
	18, // 14: clavis.v1.Clavis.ListRange:input_type -> clavis.v1.ListRangeRequest
	21, // 15: clavis.v1.Clavis.ListTrim:input_type -> clavis.v1.ListTrimRequest
	3,  // 16: clavis.v1.Clavis.Get:output_type -> clavis.v1.GetResponse
	5,  // 17: clavis.v1.Clavis.Set:output_type -> clavis.v1.SetResponse
	7,  // 18: clavis.v1.Clavis.Del:output_type -> clavis.v1.DelResponse
	9,  // 19: clavis.v1.Clavis.Ping:output_type -> clavis.v1.PingResponse
	11, // 20: clavis.v1.Clavis.ListPush:output_type -> clavis.v1.ListPushResponse
	13, // 21: clavis.v1.Clavis.ListPop:output_type -> clavis.v1.ListPopResponse
	15, // 22: clavis.v1.Clavis.ListLen:output_type -> clavis.v1.ListLenResponse
	17, // 23: clavis.v1.Clavis.ListMove:output_type -> clavis.v1.ListMoveResponse
	20, // 24: clavis.v1.Clavis.ListRange:output_type -> clavis.v1.ListRangeResponse
	22, // 25: clavis.v1.Clavis.ListTrim:output_type -> clavis.v1.ListTrimResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_clavis_proto_init() }
func file_clavis_proto_init() {
	if File_clavis_proto != nil {
		return
	}
	file_clavis_proto_msgTypes[2].OneofWrappers = []any{
		(*GetResponse_Value)(nil),
		(*GetResponse_NotFound)(nil),
		(*GetResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[3].OneofWrappers = []any{
		(*SetRequest_Create)(nil),
		(*SetRequest_Update)(nil),
		(*SetRequest_Seconds)(nil),
		(*SetRequest_Milliseconds)(nil),
		(*SetRequest_UnixSeconds)(nil),
		(*SetRequest_UnixMilliseconds)(nil),
		(*SetRequest_KeepTtl)(nil),
	}
	file_clavis_proto_msgTypes[4].OneofWrappers = []any{
		(*SetResponse_Ok)(nil),
		(*SetResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[10].OneofWrappers = []any{
		(*ListPushResponse_ListLength)(nil),
		(*ListPushResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[12].OneofWrappers = []any{
		(*ListPopResponse_Value)(nil),
		(*ListPopResponse_NotFound)(nil),
		(*ListPopResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[14].OneofWrappers = []any{
		(*ListLenResponse_Length)(nil),
		(*ListLenResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[16].OneofWrappers = []any{
		(*ListMoveResponse_MovedElement)(nil),
		(*ListMoveResponse_NotFound)(nil),
		(*ListMoveResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[19].OneofWrappers = []any{
		(*ListRangeResponse_Data)(nil),
		(*ListRangeResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[21].OneofWrappers = []any{
		(*ListTrimResponse_Ok)(nil),
		(*ListTrimResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavis_proto_rawDesc), len(file_clavis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clavis_proto_goTypes,
		DependencyIndexes: file_clavis_proto_depIdxs,
		EnumInfos:         file_clavis_proto_enumTypes,
		MessageInfos:      file_clavis_proto_msgTypes,
	}.Build()
	File_clavis_proto = out.File
	file_clavis_proto_goTypes = nil
	file_clavis_proto_depIdxs = nil
}
