// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: clavis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Clavis_Get_FullMethodName    = "/clavis.v1.Clavis/Get"
	Clavis_Set_FullMethodName    = "/clavis.v1.Clavis/Set"
	Clavis_Del_FullMethodName    = "/clavis.v1.Clavis/Del"
	Clavis_Ping_FullMethodName   = "/clavis.v1.Clavis/Ping"
	Clavis_LPush_FullMethodName  = "/clavis.v1.Clavis/LPush"
	Clavis_LPop_FullMethodName   = "/clavis.v1.Clavis/LPop"
	Clavis_LLen_FullMethodName   = "/clavis.v1.Clavis/LLen"
	Clavis_LMove_FullMethodName  = "/clavis.v1.Clavis/LMove"
	Clavis_LRange_FullMethodName = "/clavis.v1.Clavis/LRange"
	Clavis_LTrim_FullMethodName  = "/clavis.v1.Clavis/LTrim"
)

// ClavisClient is the client API for Clavis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClavisClient interface {
	// Get retrieves a value by its key.
	// Returns a response indicating whether the key was found and the value.
	// If the key does not exist, found will be false and value will be empty.
	// If the key exists, found will be true and value will contain the data.
	// If an error occurs, the response will contain an error message.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Set sets a value for a key.
	// If the key already exists, it can be set conditionally based
	// on flags (NX for "not exists", XX for "exists").
	// The response will indicate success or failure,
	// and can optionally return the old value if the key existed.
	// If an error occurs, the response will contain an error message.
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	// Del deletes a key.
	// Returns a response indicating whether the deletion was successful.
	// If the key does not exist, success is false and error contains a message.
	// If the key exists and is deleted, success is true and error is empty.
	// If an error occurs, the response will contain an error message.
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
	// Ping checks the connection to the server.
	// Returns a simple acknowledgment message.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// LPush pushes one or more values to the left end of a list.
	// Returns the length of the list after the operation.
	LPush(ctx context.Context, in *LPushRequest, opts ...grpc.CallOption) (*LPushResponse, error)
	// LPop pops the first element from a list.
	// Returns the popped value or an error if the list is
	// empty or does not exist.
	LPop(ctx context.Context, in *LPopRequest, opts ...grpc.CallOption) (*LPopResponse, error)
	// LLen retrieves the length of a list.
	// Returns the length or an error if the key does not exist or is not a list
	LLen(ctx context.Context, in *LLenRequest, opts ...grpc.CallOption) (*LLenResponse, error)
	// LMove moves an element from one list to another.
	// The element is moved from the specified side of the source
	// list to the specified side of the destination list.
	// Returns the moved element or an error if the source list is
	// empty or does not exist
	LMove(ctx context.Context, in *LMoveRequest, opts ...grpc.CallOption) (*LMoveResponse, error)
	// LRange retrieves a range of elements from a list.
	// The range is specified by start and end indices.
	// Returns the elements in the specified range or an
	// error if the key does not exist or
	// is not a list.
	LRange(ctx context.Context, in *LRangeRequest, opts ...grpc.CallOption) (*LRangeResponse, error)
	// LTrim trims a list to the specified range.
	// The range is specified by start and stop indices.
	// Returns an acknowledgment on success or an error
	// if the key does not exist or is not
	// a list.
	LTrim(ctx context.Context, in *LTrimRequest, opts ...grpc.CallOption) (*LTrimResponse, error)
}

type clavisClient struct {
	cc grpc.ClientConnInterface
}

func NewClavisClient(cc grpc.ClientConnInterface) ClavisClient {
	return &clavisClient{cc}
}

func (c *clavisClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Clavis_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, Clavis_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, Clavis_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Clavis_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) LPush(ctx context.Context, in *LPushRequest, opts ...grpc.CallOption) (*LPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LPushResponse)
	err := c.cc.Invoke(ctx, Clavis_LPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) LPop(ctx context.Context, in *LPopRequest, opts ...grpc.CallOption) (*LPopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LPopResponse)
	err := c.cc.Invoke(ctx, Clavis_LPop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) LLen(ctx context.Context, in *LLenRequest, opts ...grpc.CallOption) (*LLenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLenResponse)
	err := c.cc.Invoke(ctx, Clavis_LLen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) LMove(ctx context.Context, in *LMoveRequest, opts ...grpc.CallOption) (*LMoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LMoveResponse)
	err := c.cc.Invoke(ctx, Clavis_LMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) LRange(ctx context.Context, in *LRangeRequest, opts ...grpc.CallOption) (*LRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LRangeResponse)
	err := c.cc.Invoke(ctx, Clavis_LRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clavisClient) LTrim(ctx context.Context, in *LTrimRequest, opts ...grpc.CallOption) (*LTrimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LTrimResponse)
	err := c.cc.Invoke(ctx, Clavis_LTrim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClavisServer is the server API for Clavis service.
// All implementations must embed UnimplementedClavisServer
// for forward compatibility.
type ClavisServer interface {
	// Get retrieves a value by its key.
	// Returns a response indicating whether the key was found and the value.
	// If the key does not exist, found will be false and value will be empty.
	// If the key exists, found will be true and value will contain the data.
	// If an error occurs, the response will contain an error message.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Set sets a value for a key.
	// If the key already exists, it can be set conditionally based
	// on flags (NX for "not exists", XX for "exists").
	// The response will indicate success or failure,
	// and can optionally return the old value if the key existed.
	// If an error occurs, the response will contain an error message.
	Set(context.Context, *SetRequest) (*SetResponse, error)
	// Del deletes a key.
	// Returns a response indicating whether the deletion was successful.
	// If the key does not exist, success is false and error contains a message.
	// If the key exists and is deleted, success is true and error is empty.
	// If an error occurs, the response will contain an error message.
	Del(context.Context, *DelRequest) (*DelResponse, error)
	// Ping checks the connection to the server.
	// Returns a simple acknowledgment message.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// LPush pushes one or more values to the left end of a list.
	// Returns the length of the list after the operation.
	LPush(context.Context, *LPushRequest) (*LPushResponse, error)
	// LPop pops the first element from a list.
	// Returns the popped value or an error if the list is
	// empty or does not exist.
	LPop(context.Context, *LPopRequest) (*LPopResponse, error)
	// LLen retrieves the length of a list.
	// Returns the length or an error if the key does not exist or is not a list
	LLen(context.Context, *LLenRequest) (*LLenResponse, error)
	// LMove moves an element from one list to another.
	// The element is moved from the specified side of the source
	// list to the specified side of the destination list.
	// Returns the moved element or an error if the source list is
	// empty or does not exist
	LMove(context.Context, *LMoveRequest) (*LMoveResponse, error)
	// LRange retrieves a range of elements from a list.
	// The range is specified by start and end indices.
	// Returns the elements in the specified range or an
	// error if the key does not exist or
	// is not a list.
	LRange(context.Context, *LRangeRequest) (*LRangeResponse, error)
	// LTrim trims a list to the specified range.
	// The range is specified by start and stop indices.
	// Returns an acknowledgment on success or an error
	// if the key does not exist or is not
	// a list.
	LTrim(context.Context, *LTrimRequest) (*LTrimResponse, error)
	mustEmbedUnimplementedClavisServer()
}

// UnimplementedClavisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClavisServer struct{}

func (UnimplementedClavisServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedClavisServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedClavisServer) Del(context.Context, *DelRequest) (*DelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedClavisServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedClavisServer) LPush(context.Context, *LPushRequest) (*LPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LPush not implemented")
}
func (UnimplementedClavisServer) LPop(context.Context, *LPopRequest) (*LPopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LPop not implemented")
}
func (UnimplementedClavisServer) LLen(context.Context, *LLenRequest) (*LLenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LLen not implemented")
}
func (UnimplementedClavisServer) LMove(context.Context, *LMoveRequest) (*LMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LMove not implemented")
}
func (UnimplementedClavisServer) LRange(context.Context, *LRangeRequest) (*LRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LRange not implemented")
}
func (UnimplementedClavisServer) LTrim(context.Context, *LTrimRequest) (*LTrimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LTrim not implemented")
}
func (UnimplementedClavisServer) mustEmbedUnimplementedClavisServer() {}
func (UnimplementedClavisServer) testEmbeddedByValue()                {}

// UnsafeClavisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClavisServer will
// result in compilation errors.
type UnsafeClavisServer interface {
	mustEmbedUnimplementedClavisServer()
}

func RegisterClavisServer(s grpc.ServiceRegistrar, srv ClavisServer) {
	// If the following call pancis, it indicates UnimplementedClavisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Clavis_ServiceDesc, srv)
}

func _Clavis_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_LPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).LPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_LPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).LPush(ctx, req.(*LPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_LPop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LPopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).LPop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_LPop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).LPop(ctx, req.(*LPopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_LLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).LLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_LLen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).LLen(ctx, req.(*LLenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_LMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).LMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_LMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).LMove(ctx, req.(*LMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_LRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).LRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_LRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).LRange(ctx, req.(*LRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clavis_LTrim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LTrimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClavisServer).LTrim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clavis_LTrim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClavisServer).LTrim(ctx, req.(*LTrimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Clavis_ServiceDesc is the grpc.ServiceDesc for Clavis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clavis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clavis.v1.Clavis",
	HandlerType: (*ClavisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Clavis_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Clavis_Set_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Clavis_Del_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Clavis_Ping_Handler,
		},
		{
			MethodName: "LPush",
			Handler:    _Clavis_LPush_Handler,
		},
		{
			MethodName: "LPop",
			Handler:    _Clavis_LPop_Handler,
		},
		{
			MethodName: "LLen",
			Handler:    _Clavis_LLen_Handler,
		},
		{
			MethodName: "LMove",
			Handler:    _Clavis_LMove_Handler,
		},
		{
			MethodName: "LRange",
			Handler:    _Clavis_LRange_Handler,
		},
		{
			MethodName: "LTrim",
			Handler:    _Clavis_LTrim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clavis.proto",
}
