// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: clavis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0 // Default value, should not be used
	Side_SIDE_LEFT        Side = 1
	Side_SIDE_RIGHT       Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_LEFT",
		2: "SIDE_RIGHT",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_LEFT":        1,
		"SIDE_RIGHT":       2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_clavis_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_clavis_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{0}
}

// Empty message for requests that do not require parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_clavis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key whose value to retrieve
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_clavis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetResponse_Value
	//	*GetResponse_NotFound
	//	*GetResponse_Error
	Result        isGetResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_clavis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetResult() isGetResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		if x, ok := x.Result.(*GetResponse_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *GetResponse) GetNotFound() *Empty {
	if x != nil {
		if x, ok := x.Result.(*GetResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *GetResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*GetResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isGetResponse_Result interface {
	isGetResponse_Result()
}

type GetResponse_Value struct {
	// If the key exists, its value (arbitrary binary/text)
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type GetResponse_NotFound struct {
	// If the key does not exist
	NotFound *Empty `protobuf:"bytes,2,opt,name=not_found,json=notFound,proto3,oneof"`
}

type GetResponse_Error struct {
	// If an error occurred
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*GetResponse_Value) isGetResponse_Result() {}

func (*GetResponse_NotFound) isGetResponse_Result() {}

func (*GetResponse_Error) isGetResponse_Result() {}

type SetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to set
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value to associate with the key
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Types that are valid to be assigned to Flags:
	//
	//	*SetRequest_Nx
	//	*SetRequest_Xx
	Flags isSetRequest_Flags `protobuf_oneof:"flags"`
	// Return the old value if the key already exists
	Get bool `protobuf:"varint,5,opt,name=get,proto3" json:"get,omitempty"`
	// Optional expiration. Only one may be set.
	//
	// Types that are valid to be assigned to Expiration:
	//
	//	*SetRequest_ExSeconds
	//	*SetRequest_PxMilliseconds
	//	*SetRequest_ExatSeconds
	//	*SetRequest_PxatMilliseconds
	//	*SetRequest_KeepTtl
	Expiration    isSetRequest_Expiration `protobuf_oneof:"expiration"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_clavis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{3}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetFlags() isSetRequest_Flags {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *SetRequest) GetNx() bool {
	if x != nil {
		if x, ok := x.Flags.(*SetRequest_Nx); ok {
			return x.Nx
		}
	}
	return false
}

func (x *SetRequest) GetXx() bool {
	if x != nil {
		if x, ok := x.Flags.(*SetRequest_Xx); ok {
			return x.Xx
		}
	}
	return false
}

func (x *SetRequest) GetGet() bool {
	if x != nil {
		return x.Get
	}
	return false
}

func (x *SetRequest) GetExpiration() isSetRequest_Expiration {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *SetRequest) GetExSeconds() uint32 {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_ExSeconds); ok {
			return x.ExSeconds
		}
	}
	return 0
}

func (x *SetRequest) GetPxMilliseconds() uint64 {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_PxMilliseconds); ok {
			return x.PxMilliseconds
		}
	}
	return 0
}

func (x *SetRequest) GetExatSeconds() uint64 {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_ExatSeconds); ok {
			return x.ExatSeconds
		}
	}
	return 0
}

func (x *SetRequest) GetPxatMilliseconds() uint64 {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_PxatMilliseconds); ok {
			return x.PxatMilliseconds
		}
	}
	return 0
}

func (x *SetRequest) GetKeepTtl() bool {
	if x != nil {
		if x, ok := x.Expiration.(*SetRequest_KeepTtl); ok {
			return x.KeepTtl
		}
	}
	return false
}

type isSetRequest_Flags interface {
	isSetRequest_Flags()
}

type SetRequest_Nx struct {
	// Set the key only if it does not already exist (NX)
	Nx bool `protobuf:"varint,3,opt,name=nx,proto3,oneof"`
}

type SetRequest_Xx struct {
	// Set the key only if it already exists (XX)
	Xx bool `protobuf:"varint,4,opt,name=xx,proto3,oneof"`
}

func (*SetRequest_Nx) isSetRequest_Flags() {}

func (*SetRequest_Xx) isSetRequest_Flags() {}

type isSetRequest_Expiration interface {
	isSetRequest_Expiration()
}

type SetRequest_ExSeconds struct {
	// Expire after this many seconds (EX)
	ExSeconds uint32 `protobuf:"varint,6,opt,name=ex_seconds,json=exSeconds,proto3,oneof"`
}

type SetRequest_PxMilliseconds struct {
	// Expire after this many milliseconds (PX)
	PxMilliseconds uint64 `protobuf:"varint,7,opt,name=px_milliseconds,json=pxMilliseconds,proto3,oneof"`
}

type SetRequest_ExatSeconds struct {
	// Set the specific expiration time (EXAT)
	ExatSeconds uint64 `protobuf:"varint,8,opt,name=exat_seconds,json=exatSeconds,proto3,oneof"`
}

type SetRequest_PxatMilliseconds struct {
	// Set the specific expiration time in milliseconds (PXAT)
	PxatMilliseconds uint64 `protobuf:"varint,9,opt,name=pxat_milliseconds,json=pxatMilliseconds,proto3,oneof"`
}

type SetRequest_KeepTtl struct {
	// Keep the key alive indefinitely (KEEPTTL)
	KeepTtl bool `protobuf:"varint,10,opt,name=keep_ttl,json=keepTtl,proto3,oneof"`
}

func (*SetRequest_ExSeconds) isSetRequest_Expiration() {}

func (*SetRequest_PxMilliseconds) isSetRequest_Expiration() {}

func (*SetRequest_ExatSeconds) isSetRequest_Expiration() {}

func (*SetRequest_PxatMilliseconds) isSetRequest_Expiration() {}

func (*SetRequest_KeepTtl) isSetRequest_Expiration() {}

type SetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OK on success, or an error message
	//
	// Types that are valid to be assigned to Result:
	//
	//	*SetResponse_Ok
	//	*SetResponse_Error
	Result        isSetResponse_Result `protobuf_oneof:"result"`
	OldValue      []byte               `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3,oneof" json:"old_value,omitempty"` // Old value if get was true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_clavis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{4}
}

func (x *SetResponse) GetResult() isSetResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SetResponse) GetOk() string {
	if x != nil {
		if x, ok := x.Result.(*SetResponse_Ok); ok {
			return x.Ok
		}
	}
	return ""
}

func (x *SetResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*SetResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *SetResponse) GetOldValue() []byte {
	if x != nil {
		return x.OldValue
	}
	return nil
}

type isSetResponse_Result interface {
	isSetResponse_Result()
}

type SetResponse_Ok struct {
	Ok string `protobuf:"bytes,1,opt,name=ok,proto3,oneof"` // usually "OK"
}

type SetResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Redis error reply
}

func (*SetResponse_Ok) isSetResponse_Result() {}

func (*SetResponse_Error) isSetResponse_Result() {}

type DelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key to delete
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_clavis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{5}
}

func (x *DelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates whether the deletion was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the operation fails
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_clavis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{6}
}

func (x *DelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_clavis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{7}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response to a ping request, typically just an acknowledgment
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // e.g., "PONG"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_clavis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LPushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list to which values will be pushed
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Values to push to the list
	Values        [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"` // Values to push to the list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPushRequest) Reset() {
	*x = LPushRequest{}
	mi := &file_clavis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushRequest) ProtoMessage() {}

func (x *LPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushRequest.ProtoReflect.Descriptor instead.
func (*LPushRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{9}
}

func (x *LPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LPushRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type LPushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*LPushResponse_ListLength
	//	*LPushResponse_Error
	Result        isLPushResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPushResponse) Reset() {
	*x = LPushResponse{}
	mi := &file_clavis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushResponse) ProtoMessage() {}

func (x *LPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushResponse.ProtoReflect.Descriptor instead.
func (*LPushResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{10}
}

func (x *LPushResponse) GetResult() isLPushResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LPushResponse) GetListLength() int64 {
	if x != nil {
		if x, ok := x.Result.(*LPushResponse_ListLength); ok {
			return x.ListLength
		}
	}
	return 0
}

func (x *LPushResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*LPushResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isLPushResponse_Result interface {
	isLPushResponse_Result()
}

type LPushResponse_ListLength struct {
	// Length of the list after push
	ListLength int64 `protobuf:"varint,1,opt,name=list_length,json=listLength,proto3,oneof"`
}

type LPushResponse_Error struct {
	// If the key does not exist or is not a list
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*LPushResponse_ListLength) isLPushResponse_Result() {}

func (*LPushResponse_Error) isLPushResponse_Result() {}

type LPopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list from which to pop the first element
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPopRequest) Reset() {
	*x = LPopRequest{}
	mi := &file_clavis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopRequest) ProtoMessage() {}

func (x *LPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopRequest.ProtoReflect.Descriptor instead.
func (*LPopRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{11}
}

func (x *LPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LPopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*LPopResponse_Value
	//	*LPopResponse_NotFound
	//	*LPopResponse_Error
	Result        isLPopResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPopResponse) Reset() {
	*x = LPopResponse{}
	mi := &file_clavis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopResponse) ProtoMessage() {}

func (x *LPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopResponse.ProtoReflect.Descriptor instead.
func (*LPopResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{12}
}

func (x *LPopResponse) GetResult() isLPopResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LPopResponse) GetValue() []byte {
	if x != nil {
		if x, ok := x.Result.(*LPopResponse_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *LPopResponse) GetNotFound() *Empty {
	if x != nil {
		if x, ok := x.Result.(*LPopResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *LPopResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*LPopResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isLPopResponse_Result interface {
	isLPopResponse_Result()
}

type LPopResponse_Value struct {
	// First element popped
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type LPopResponse_NotFound struct {
	// If list is empty or key doesn't exist
	NotFound *Empty `protobuf:"bytes,2,opt,name=not_found,json=notFound,proto3,oneof"`
}

type LPopResponse_Error struct {
	// If an error occurred
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*LPopResponse_Value) isLPopResponse_Result() {}

func (*LPopResponse_NotFound) isLPopResponse_Result() {}

func (*LPopResponse_Error) isLPopResponse_Result() {}

type LLenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list whose length to retrieve
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLenRequest) Reset() {
	*x = LLenRequest{}
	mi := &file_clavis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLenRequest) ProtoMessage() {}

func (x *LLenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLenRequest.ProtoReflect.Descriptor instead.
func (*LLenRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{13}
}

func (x *LLenRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LLenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*LLenResponse_Length
	//	*LLenResponse_Error
	Result        isLLenResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLenResponse) Reset() {
	*x = LLenResponse{}
	mi := &file_clavis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLenResponse) ProtoMessage() {}

func (x *LLenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLenResponse.ProtoReflect.Descriptor instead.
func (*LLenResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{14}
}

func (x *LLenResponse) GetResult() isLLenResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LLenResponse) GetLength() int64 {
	if x != nil {
		if x, ok := x.Result.(*LLenResponse_Length); ok {
			return x.Length
		}
	}
	return 0
}

func (x *LLenResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*LLenResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isLLenResponse_Result interface {
	isLLenResponse_Result()
}

type LLenResponse_Length struct {
	// Length of the list
	Length int64 `protobuf:"varint,1,opt,name=length,proto3,oneof"`
}

type LLenResponse_Error struct {
	// If the key does not exist or is not a list
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*LLenResponse_Length) isLLenResponse_Result() {}

func (*LLenResponse_Error) isLLenResponse_Result() {}

type LMoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The keys of the source and destination lists
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// The key of the destination list
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	// LEFT or RIGHT
	From Side `protobuf:"varint,3,opt,name=from,proto3,enum=clavis.v1.Side" json:"from,omitempty"`
	// LEFT or RIGHT
	To            Side `protobuf:"varint,4,opt,name=to,proto3,enum=clavis.v1.Side" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LMoveRequest) Reset() {
	*x = LMoveRequest{}
	mi := &file_clavis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LMoveRequest) ProtoMessage() {}

func (x *LMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LMoveRequest.ProtoReflect.Descriptor instead.
func (*LMoveRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{15}
}

func (x *LMoveRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LMoveRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *LMoveRequest) GetFrom() Side {
	if x != nil {
		return x.From
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *LMoveRequest) GetTo() Side {
	if x != nil {
		return x.To
	}
	return Side_SIDE_UNSPECIFIED
}

type LMoveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*LMoveResponse_MovedElement
	//	*LMoveResponse_NotFound
	//	*LMoveResponse_Error
	Result        isLMoveResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LMoveResponse) Reset() {
	*x = LMoveResponse{}
	mi := &file_clavis_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LMoveResponse) ProtoMessage() {}

func (x *LMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LMoveResponse.ProtoReflect.Descriptor instead.
func (*LMoveResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{16}
}

func (x *LMoveResponse) GetResult() isLMoveResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LMoveResponse) GetMovedElement() []byte {
	if x != nil {
		if x, ok := x.Result.(*LMoveResponse_MovedElement); ok {
			return x.MovedElement
		}
	}
	return nil
}

func (x *LMoveResponse) GetNotFound() *Empty {
	if x != nil {
		if x, ok := x.Result.(*LMoveResponse_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *LMoveResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*LMoveResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isLMoveResponse_Result interface {
	isLMoveResponse_Result()
}

type LMoveResponse_MovedElement struct {
	// The element moved from source to destination
	MovedElement []byte `protobuf:"bytes,1,opt,name=moved_element,json=movedElement,proto3,oneof"`
}

type LMoveResponse_NotFound struct {
	// If the source list is empty or does not exist
	NotFound *Empty `protobuf:"bytes,2,opt,name=not_found,json=notFound,proto3,oneof"`
}

type LMoveResponse_Error struct {
	// If an error occurred
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*LMoveResponse_MovedElement) isLMoveResponse_Result() {}

func (*LMoveResponse_NotFound) isLMoveResponse_Result() {}

func (*LMoveResponse_Error) isLMoveResponse_Result() {}

type LRangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list to retrieve elements from
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Start index (inclusive)
	Start int64 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	// End index (inclusive)
	End           int64 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRangeRequest) Reset() {
	*x = LRangeRequest{}
	mi := &file_clavis_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeRequest) ProtoMessage() {}

func (x *LRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeRequest.ProtoReflect.Descriptor instead.
func (*LRangeRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{17}
}

func (x *LRangeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LRangeRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LRangeRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type LRangeData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The elements in the specified range
	Elements      [][]byte `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRangeData) Reset() {
	*x = LRangeData{}
	mi := &file_clavis_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRangeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeData) ProtoMessage() {}

func (x *LRangeData) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeData.ProtoReflect.Descriptor instead.
func (*LRangeData) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{18}
}

func (x *LRangeData) GetElements() [][]byte {
	if x != nil {
		return x.Elements
	}
	return nil
}

type LRangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*LRangeResponse_Data
	//	*LRangeResponse_Error
	Result        isLRangeResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRangeResponse) Reset() {
	*x = LRangeResponse{}
	mi := &file_clavis_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeResponse) ProtoMessage() {}

func (x *LRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeResponse.ProtoReflect.Descriptor instead.
func (*LRangeResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{19}
}

func (x *LRangeResponse) GetResult() isLRangeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LRangeResponse) GetData() *LRangeData {
	if x != nil {
		if x, ok := x.Result.(*LRangeResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *LRangeResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*LRangeResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isLRangeResponse_Result interface {
	isLRangeResponse_Result()
}

type LRangeResponse_Data struct {
	// The elements in the specified range
	Data *LRangeData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type LRangeResponse_Error struct {
	// If the key does not exist or is not a list
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*LRangeResponse_Data) isLRangeResponse_Result() {}

func (*LRangeResponse_Error) isLRangeResponse_Result() {}

type LTrimRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the list to trim
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Start index (inclusive)
	Start int64 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	// End index (inclusive)
	Stop          int64 `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LTrimRequest) Reset() {
	*x = LTrimRequest{}
	mi := &file_clavis_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LTrimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTrimRequest) ProtoMessage() {}

func (x *LTrimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTrimRequest.ProtoReflect.Descriptor instead.
func (*LTrimRequest) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{20}
}

func (x *LTrimRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LTrimRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LTrimRequest) GetStop() int64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

type LTrimResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*LTrimResponse_Ok
	//	*LTrimResponse_Error
	Result        isLTrimResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LTrimResponse) Reset() {
	*x = LTrimResponse{}
	mi := &file_clavis_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LTrimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LTrimResponse) ProtoMessage() {}

func (x *LTrimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clavis_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LTrimResponse.ProtoReflect.Descriptor instead.
func (*LTrimResponse) Descriptor() ([]byte, []int) {
	return file_clavis_proto_rawDescGZIP(), []int{21}
}

func (x *LTrimResponse) GetResult() isLTrimResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LTrimResponse) GetOk() string {
	if x != nil {
		if x, ok := x.Result.(*LTrimResponse_Ok); ok {
			return x.Ok
		}
	}
	return ""
}

func (x *LTrimResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*LTrimResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isLTrimResponse_Result interface {
	isLTrimResponse_Result()
}

type LTrimResponse_Ok struct {
	Ok string `protobuf:"bytes,1,opt,name=ok,proto3,oneof"` // usually "OK"
}

type LTrimResponse_Error struct {
	// If the key does not exist or is not a list
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*LTrimResponse_Ok) isLTrimResponse_Result() {}

func (*LTrimResponse_Error) isLTrimResponse_Result() {}

var File_clavis_proto protoreflect.FileDescriptor

const file_clavis_proto_rawDesc = "" +
	"\n" +
	"\fclavis.proto\x12\tclavis.v1\"\a\n" +
	"\x05Empty\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"x\n" +
	"\vGetResponse\x12\x16\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x12/\n" +
	"\tnot_found\x18\x02 \x01(\v2\x10.clavis.v1.EmptyH\x00R\bnotFound\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"\xbe\x02\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x02nx\x18\x03 \x01(\bH\x00R\x02nx\x12\x10\n" +
	"\x02xx\x18\x04 \x01(\bH\x00R\x02xx\x12\x10\n" +
	"\x03get\x18\x05 \x01(\bR\x03get\x12\x1f\n" +
	"\n" +
	"ex_seconds\x18\x06 \x01(\rH\x01R\texSeconds\x12)\n" +
	"\x0fpx_milliseconds\x18\a \x01(\x04H\x01R\x0epxMilliseconds\x12#\n" +
	"\fexat_seconds\x18\b \x01(\x04H\x01R\vexatSeconds\x12-\n" +
	"\x11pxat_milliseconds\x18\t \x01(\x04H\x01R\x10pxatMilliseconds\x12\x1b\n" +
	"\bkeep_ttl\x18\n" +
	" \x01(\bH\x01R\akeepTtlB\a\n" +
	"\x05flagsB\f\n" +
	"\n" +
	"expiration\"q\n" +
	"\vSetResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\tH\x00R\x02ok\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x12 \n" +
	"\told_value\x18\x03 \x01(\fH\x01R\boldValue\x88\x01\x01B\b\n" +
	"\x06resultB\f\n" +
	"\n" +
	"_old_value\"\x1e\n" +
	"\n" +
	"DelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"=\n" +
	"\vDelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"8\n" +
	"\fLPushRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\fR\x06values\"T\n" +
	"\rLPushResponse\x12!\n" +
	"\vlist_length\x18\x01 \x01(\x03H\x00R\n" +
	"listLength\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"\x1f\n" +
	"\vLPopRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"y\n" +
	"\fLPopResponse\x12\x16\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x12/\n" +
	"\tnot_found\x18\x02 \x01(\v2\x10.clavis.v1.EmptyH\x00R\bnotFound\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"\x1f\n" +
	"\vLLenRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"J\n" +
	"\fLLenResponse\x12\x18\n" +
	"\x06length\x18\x01 \x01(\x03H\x00R\x06length\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"\x8e\x01\n" +
	"\fLMoveRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12#\n" +
	"\x04from\x18\x03 \x01(\x0e2\x0f.clavis.v1.SideR\x04from\x12\x1f\n" +
	"\x02to\x18\x04 \x01(\x0e2\x0f.clavis.v1.SideR\x02to\"\x89\x01\n" +
	"\rLMoveResponse\x12%\n" +
	"\rmoved_element\x18\x01 \x01(\fH\x00R\fmovedElement\x12/\n" +
	"\tnot_found\x18\x02 \x01(\v2\x10.clavis.v1.EmptyH\x00R\bnotFound\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"I\n" +
	"\rLRangeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x03R\x03end\"(\n" +
	"\n" +
	"LRangeData\x12\x1a\n" +
	"\belements\x18\x01 \x03(\fR\belements\"_\n" +
	"\x0eLRangeResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x15.clavis.v1.LRangeDataH\x00R\x04data\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"J\n" +
	"\fLTrimRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x12\n" +
	"\x04stop\x18\x03 \x01(\x03R\x04stop\"C\n" +
	"\rLTrimResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\tH\x00R\x02ok\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result*;\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSIDE_LEFT\x10\x01\x12\x0e\n" +
	"\n" +
	"SIDE_RIGHT\x10\x022\xdc\x04\n" +
	"\x06Clavis\x126\n" +
	"\x03Get\x12\x15.clavis.v1.GetRequest\x1a\x16.clavis.v1.GetResponse\"\x00\x126\n" +
	"\x03Set\x12\x15.clavis.v1.SetRequest\x1a\x16.clavis.v1.SetResponse\"\x00\x126\n" +
	"\x03Del\x12\x15.clavis.v1.DelRequest\x1a\x16.clavis.v1.DelResponse\"\x00\x129\n" +
	"\x04Ping\x12\x16.clavis.v1.PingRequest\x1a\x17.clavis.v1.PingResponse\"\x00\x12<\n" +
	"\x05LPush\x12\x17.clavis.v1.LPushRequest\x1a\x18.clavis.v1.LPushResponse\"\x00\x129\n" +
	"\x04LPop\x12\x16.clavis.v1.LPopRequest\x1a\x17.clavis.v1.LPopResponse\"\x00\x129\n" +
	"\x04LLen\x12\x16.clavis.v1.LLenRequest\x1a\x17.clavis.v1.LLenResponse\"\x00\x12<\n" +
	"\x05LMove\x12\x17.clavis.v1.LMoveRequest\x1a\x18.clavis.v1.LMoveResponse\"\x00\x12?\n" +
	"\x06LRange\x12\x18.clavis.v1.LRangeRequest\x1a\x19.clavis.v1.LRangeResponse\"\x00\x12<\n" +
	"\x05LTrim\x12\x17.clavis.v1.LTrimRequest\x1a\x18.clavis.v1.LTrimResponse\"\x00B\vZ\tpkg/protob\x06proto3"

var (
	file_clavis_proto_rawDescOnce sync.Once
	file_clavis_proto_rawDescData []byte
)

func file_clavis_proto_rawDescGZIP() []byte {
	file_clavis_proto_rawDescOnce.Do(func() {
		file_clavis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clavis_proto_rawDesc), len(file_clavis_proto_rawDesc)))
	})
	return file_clavis_proto_rawDescData
}

var file_clavis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clavis_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_clavis_proto_goTypes = []any{
	(Side)(0),              // 0: clavis.v1.Side
	(*Empty)(nil),          // 1: clavis.v1.Empty
	(*GetRequest)(nil),     // 2: clavis.v1.GetRequest
	(*GetResponse)(nil),    // 3: clavis.v1.GetResponse
	(*SetRequest)(nil),     // 4: clavis.v1.SetRequest
	(*SetResponse)(nil),    // 5: clavis.v1.SetResponse
	(*DelRequest)(nil),     // 6: clavis.v1.DelRequest
	(*DelResponse)(nil),    // 7: clavis.v1.DelResponse
	(*PingRequest)(nil),    // 8: clavis.v1.PingRequest
	(*PingResponse)(nil),   // 9: clavis.v1.PingResponse
	(*LPushRequest)(nil),   // 10: clavis.v1.LPushRequest
	(*LPushResponse)(nil),  // 11: clavis.v1.LPushResponse
	(*LPopRequest)(nil),    // 12: clavis.v1.LPopRequest
	(*LPopResponse)(nil),   // 13: clavis.v1.LPopResponse
	(*LLenRequest)(nil),    // 14: clavis.v1.LLenRequest
	(*LLenResponse)(nil),   // 15: clavis.v1.LLenResponse
	(*LMoveRequest)(nil),   // 16: clavis.v1.LMoveRequest
	(*LMoveResponse)(nil),  // 17: clavis.v1.LMoveResponse
	(*LRangeRequest)(nil),  // 18: clavis.v1.LRangeRequest
	(*LRangeData)(nil),     // 19: clavis.v1.LRangeData
	(*LRangeResponse)(nil), // 20: clavis.v1.LRangeResponse
	(*LTrimRequest)(nil),   // 21: clavis.v1.LTrimRequest
	(*LTrimResponse)(nil),  // 22: clavis.v1.LTrimResponse
}
var file_clavis_proto_depIdxs = []int32{
	1,  // 0: clavis.v1.GetResponse.not_found:type_name -> clavis.v1.Empty
	1,  // 1: clavis.v1.LPopResponse.not_found:type_name -> clavis.v1.Empty
	0,  // 2: clavis.v1.LMoveRequest.from:type_name -> clavis.v1.Side
	0,  // 3: clavis.v1.LMoveRequest.to:type_name -> clavis.v1.Side
	1,  // 4: clavis.v1.LMoveResponse.not_found:type_name -> clavis.v1.Empty
	19, // 5: clavis.v1.LRangeResponse.data:type_name -> clavis.v1.LRangeData
	2,  // 6: clavis.v1.Clavis.Get:input_type -> clavis.v1.GetRequest
	4,  // 7: clavis.v1.Clavis.Set:input_type -> clavis.v1.SetRequest
	6,  // 8: clavis.v1.Clavis.Del:input_type -> clavis.v1.DelRequest
	8,  // 9: clavis.v1.Clavis.Ping:input_type -> clavis.v1.PingRequest
	10, // 10: clavis.v1.Clavis.LPush:input_type -> clavis.v1.LPushRequest
	12, // 11: clavis.v1.Clavis.LPop:input_type -> clavis.v1.LPopRequest
	14, // 12: clavis.v1.Clavis.LLen:input_type -> clavis.v1.LLenRequest
	16, // 13: clavis.v1.Clavis.LMove:input_type -> clavis.v1.LMoveRequest
	18, // 14: clavis.v1.Clavis.LRange:input_type -> clavis.v1.LRangeRequest
	21, // 15: clavis.v1.Clavis.LTrim:input_type -> clavis.v1.LTrimRequest
	3,  // 16: clavis.v1.Clavis.Get:output_type -> clavis.v1.GetResponse
	5,  // 17: clavis.v1.Clavis.Set:output_type -> clavis.v1.SetResponse
	7,  // 18: clavis.v1.Clavis.Del:output_type -> clavis.v1.DelResponse
	9,  // 19: clavis.v1.Clavis.Ping:output_type -> clavis.v1.PingResponse
	11, // 20: clavis.v1.Clavis.LPush:output_type -> clavis.v1.LPushResponse
	13, // 21: clavis.v1.Clavis.LPop:output_type -> clavis.v1.LPopResponse
	15, // 22: clavis.v1.Clavis.LLen:output_type -> clavis.v1.LLenResponse
	17, // 23: clavis.v1.Clavis.LMove:output_type -> clavis.v1.LMoveResponse
	20, // 24: clavis.v1.Clavis.LRange:output_type -> clavis.v1.LRangeResponse
	22, // 25: clavis.v1.Clavis.LTrim:output_type -> clavis.v1.LTrimResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_clavis_proto_init() }
func file_clavis_proto_init() {
	if File_clavis_proto != nil {
		return
	}
	file_clavis_proto_msgTypes[2].OneofWrappers = []any{
		(*GetResponse_Value)(nil),
		(*GetResponse_NotFound)(nil),
		(*GetResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[3].OneofWrappers = []any{
		(*SetRequest_Nx)(nil),
		(*SetRequest_Xx)(nil),
		(*SetRequest_ExSeconds)(nil),
		(*SetRequest_PxMilliseconds)(nil),
		(*SetRequest_ExatSeconds)(nil),
		(*SetRequest_PxatMilliseconds)(nil),
		(*SetRequest_KeepTtl)(nil),
	}
	file_clavis_proto_msgTypes[4].OneofWrappers = []any{
		(*SetResponse_Ok)(nil),
		(*SetResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[10].OneofWrappers = []any{
		(*LPushResponse_ListLength)(nil),
		(*LPushResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[12].OneofWrappers = []any{
		(*LPopResponse_Value)(nil),
		(*LPopResponse_NotFound)(nil),
		(*LPopResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[14].OneofWrappers = []any{
		(*LLenResponse_Length)(nil),
		(*LLenResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[16].OneofWrappers = []any{
		(*LMoveResponse_MovedElement)(nil),
		(*LMoveResponse_NotFound)(nil),
		(*LMoveResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[19].OneofWrappers = []any{
		(*LRangeResponse_Data)(nil),
		(*LRangeResponse_Error)(nil),
	}
	file_clavis_proto_msgTypes[21].OneofWrappers = []any{
		(*LTrimResponse_Ok)(nil),
		(*LTrimResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clavis_proto_rawDesc), len(file_clavis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clavis_proto_goTypes,
		DependencyIndexes: file_clavis_proto_depIdxs,
		EnumInfos:         file_clavis_proto_enumTypes,
		MessageInfos:      file_clavis_proto_msgTypes,
	}.Build()
	File_clavis_proto = out.File
	file_clavis_proto_goTypes = nil
	file_clavis_proto_depIdxs = nil
}
